[package]
name = "rusile"
description = "Rusty components for the SILE typesetter"
readme = "../README.md"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
build = "../build-aux/module.rs"

[lib]
crate-type = ["rlib", "cdylib", "staticlib"]

[features]
default = []
lua54 = ["mlua/lua54"]
lua53 = ["mlua/lua53"]
lua52 = ["mlua/lua52"]
lua51 = ["mlua/lua51"]
luajit = ["mlua/luajit"]
vendored = ["mlua/vendored"]

[dependencies.sile]
workspace = true

[dependencies.mlua]
workspace = true
features = ["macros", "module"]
