name: Deploy

on:
  push:
    branches:
      - master
      - develop
      - rel*
    tags:
      - latest
      - v*

jobs:

  ghcr:
    strategy:
      fail-fast: false
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libluajit-5.1-dev luajit luarocks
      - name: Configure
        run: |
          echo "REF=${GITHUB_REF##refs/*/}" >> $GITHUB_ENV
          ./bootstrap.sh
          ./configure \
            --enable-developer-mode \
            --without-harfbuzz \
            --disable-font-variations \
            BSDTAR=false \
            BUSTED=false \
            DELTA=false \
            FCMATCH=true \
            LDOC=false \
            LUACHECK=false \
            LUAROCKS=false \
            NIX=false \
            PDFINFO=false \
            STYLUA=false
      - name: Publish Docker Image to GH Container Registry
        run: |
          make docker-build-push
        env:
          DOCKER_REGISTRY: ghcr.io
          DOCKER_REPO: ${{ github.repository }}
          DOCKER_TAG: ${{ env.REF }}
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PAT: ${{ secrets.CR_SILE_TYPESETTER }}
